AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: marketplace-neg-3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6
    Environment:
      Variables:
        OPENAI_API_KEY: !Ref OpenAIApiKey


Resources:
  MarketplaceNegFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        Http:
          Type: Api
          Properties:
            Path: "/"
            Method: Any

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MarketplaceNegApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MarketplaceNegFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MarketplaceNegFunction.Arn
  MarketplaceNegFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MarketplaceNegFunctionRole.Arn

Parameters:
  OpenAIApiKey:
    Type: String

  
