version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "marketplace-neg-4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xuwllydo99rm"
s3_prefix = "marketplace-neg-4"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
